marlin: update kernel prebuilt
0a417d7a ANDROID: binder: improve priority inheritance for oneway.
51209c9b ANDROID: binder: add min sched_policy to node.
19392041 ANDROID: binder: Add tracing for binder priority inheritance.
14788a38 ANDROID: binder: do proper priority inheritance checking.
a95a09c2 ANDROID: sdcardfs: Don't iput if we didn't igrab
d5e5d032 smbcharger: do not report usb type based on pd/typec
e0559321 Merge 3.18.43 into android-msm-marlin-3.18
f28df764 Merge 3.18.43 into android-msm-marlin-3.18
bae4b025 Merge 3.18.42 into android-msm-marlin-3.18
a4e2ced0 Merge 3.18.41 into android-msm-marlin-3.18
ce0c7f19 Merge 3.18.40 into android-msm-marlin-3.18
11b8cfc0 Merge 3.18.39 into android-msm-marlin-3.18
ae689df1 Merge 3.18.38 into android-msm-marlin-3.18
f4718036 netfilter: x_tables: speed up jump target validation
5ec8a8c8 Merge rest of 3.18.37 into android-msm-marlin-3.18
3cab355c Linux 3.18.43
02ce1fd7 openrisc: fix the fix of copy_from_user()
fb808fa0 ARM: orion: convert the irq_reg_{readl,writel} calls to the new API
db9b2a38 avr32: fix 'undefined reference to `___copy_from_user'
54e7defb hexagon: Fix build failures in linux-next
f6e672ad block: Do a full clone when splitting discard bios
31714bce btrfs: ensure that file descriptor used with subvol ioctls is a dir
400f32af fix fault_in_multipages_...() on architectures with no-op access_ok()
1108f703 ocfs2: fix start offset to ocfs2_zero_range_for_truncate()
8a781b2e fanotify: fix list corruption in fanotify_get_response()
05eb9c07 fsnotify: add a way to stop queueing events on group shutdown
8a66ed31 autofs: use dentry flags to block walks during expire
14386af6 autofs races
de32bc4c ocfs2/dlm: fix race between convert and migration
0b5f2bd0 can: flexcan: fix resume function
86945428 USB: change bInterval default to 10 ms
e58d9a82 fix minor infoleak in get_user_ex()
0772cbae avr32: fix copy_from_user()
c352b42e microblaze: fix __get_user()
d31b0dcf microblaze: fix copy_from_user()
ba08781d m32r: fix __get_user()
f27aa24d blackfin: fix copy_from_user()
9050993a sparc32: fix copy_from_user()
8bd2ef70 sh: fix copy_from_user()
94000fc8 sh64: failing __get_user() should zero
c1c77a5f score: fix copy_from_user() and friends
68f1e32c score: fix __get_user/get_user
0cdee92f s390: get_user() should zero on failure
1b228faa ppc32: fix copy_from_user()
6c696327 parisc: fix copy_from_user()
499e590c openrisc: fix copy_from_user()
8260a515 mn10300: copy_from_user() should zero on access_ok() failure...
f17364dd mn10300: failing __get_user() and get_user() should zero
c99e37cd mips: copy_from_user() must zero the destination on access_ok() failure
09baa6b1 ARC: uaccess: get_user to zero out dest in cause of fault
9a34b2a7 metag: copy_from_user() should zero the destination on access_ok() failure
ddc84f7b ia64: copy_from_user() should zero the destination on access_ok() failure
591ca382 hexagon: fix strncpy_from_user() error return
a4bc5779 frv: fix clear_user()
f13847df asm-generic: make get_user() clear the destination on errors
a0ed243c asm-generic: {get,put}_user ptr argument evaluate only 1 time
93e5a11e nl80211: validate number of probe response CSA counters
bc6285a7 MIPS: Add a missing ".set pop" in an early commit
790e65fd genirq: Provide irq_gc_{lock_irqsave,unlock_irqrestore}() helpers
b5937a54 genirq: Generic chip: Change irq_reg_{readl,writel} arguments
75175017 MIPS: paravirt: Fix undefined reference to smp_bootstrap
e47705fb crypto: arm64/aes-ctr - fix NULL dereference in tail processing
4f17ddb1 crypto: skcipher - Fix blkcipher walk OOM crash
f5c698a8 USB: serial: simple: add support for another Infineon flashloader
11e9b4ed asm-generic: make copy_from_user() zero the destination properly
62fc2f90 arm64: spinlocks: implement smp_mb__before_spinlock() as smp_mb()
f4e1eb5d kvm-arm: Unmap shadow pagetables properly
1a30ab34 ALSA: timer: Fix zero-division by continue of uninitialized instance
1174014a ALSA: timer: Call notifier in the same spinlock
10494714 xhci: fix null pointer dereference in stop command timeout function
029a0cab powerpc/mm: Don't alias user region to other regions below PAGE_OFFSET
87af205b crypto: cryptd - initialize child shash_desc on import
f6692fc5 ipv6: addrconf: fix dev refcont leak when DAD failed
52e5087c Btrfs: remove root_log_ctx from ctx list before btrfs_sync_log returns
a55325e1 Btrfs: add missing blk_finish_plug in btrfs_sync_log()
f5518a3e usb: renesas_usbhs: fix clearing the {BRDY,BEMP}STS condition
fb4064af sched/core: Fix a race between try_to_wake_up() and a woken up task
a2b26854 iio: accel: kxsd9: Fix scaling bug
7107bc8e ALSA: fireworks: accessing to user space outside spinlock
3294908b ARM: imx6: add missing BM_CLPCR_BYPASS_PMIC_READY setting for imx6sx
6000f01b ALSA: usb-audio: Add sample rate inquiry quirk for B850V3 CP2114
14e3a786 ALSA: timer: fix NULL pointer dereference on memory allocation failure
a987c625 ALSA: timer: fix division by zero after SNDRV_TIMER_IOCTL_CONTINUE
d0a2d410 ARM: kirkwood: ib62x0: fix size of u-boot environment partition
cb366258 bus: arm-ccn: Fix XP watchpoint settings bitmask
703dd66f bus: arm-ccn: Do not attempt to configure XPs for cycle counter
26a0e0c2 Revert "wext: Fix 32 bit iwpriv compatibility issue with 64 bit Kernel"
177b4898 ARM: OMAP3: hwmod data: Add sysc information for DSI
2ee6abbd ovl: fix workdir creation
7cc3f9b1 MIPS: KVM: Check for pfn noslot case
a8e20281 Linux 3.18.42
cac5e8f4 Revert "ARC: mm: don't loose PTE_SPECIAL in pte_modify()"
7c17facc x86/AMD: Apply erratum 665 on machines without a BIOS fix
18ec3adc x86/paravirt: Do not trace _paravirt_ident_*() functions
f4572434 ovl: listxattr: use strnlen()
cc318bc6 ovl: remove posix_acl_default from workdir
0b764b2e kernfs: don't depend on d_find_any_alias() when generating notifications
01d0c457 dm crypt: fix free of bad values after tfm allocation failure
ab50c732 dm crypt: fix error with too large bios
13312f0f NFSv4.x: Fix a refcount leak in nfs_callback_up_net
4ff77f22 xfs: fix superblock inprogress check
b735daae USB: serial: option: add WeTelecom 0x6802 and 0x6803 products
a6eba2f7 USB: serial: option: add WeTelecom WM-D200
e066faf1 USB: avoid left shift by -1
93c7ae51 iio: accel: kxsd9: Fix raw read return
6ef28f2f staging: comedi: ni_mio_common: fix AO inttrig backwards compatibility
985f3f23 staging: comedi: ni_mio_common: fix wrong insn_write handler
d8107af0 staging: comedi: daqboard2000: bug fix board type matching code
178bc908 USB: serial: mos7840: fix non-atomic allocation in write path
a1147c77 USB: serial: mos7720: fix non-atomic allocation in write path
87fe0cd8 cpuset: make sure new tasks conform to the current config of the cpuset
5edbe377 ovl: don't copy up opaqueness
ade4ba0d ext4: validate that metadata blocks do not overlap superblock
db9e37a1 [PATCH] arm: fix handling of F_OFD_... in oabi_fcntl64()
e9e1b43e Linux 3.18.41
8a1a4c7a PCI: Limit config space size for Netronome NFP4000
1935e837 PCI: Add Netronome NFP4000 PF device ID
bfb058eb PCI: Limit config space size for Netronome NFP6000 family
7a5b93be PCI: Add Netronome vendor and device IDs
ab2b9d85 PCI: Support PCIe devices with short cfg_size
47e617f9 net: fec: fix NULL pointer dereference in fec_enet_timeout_work
5de0c13e fs/seq_file: fix out-of-bounds read
c8ca488f clocksource/drivers/sun4i: Clear interrupts after stopping timer in probe function
82d1894c dm flakey: fix reads to be issued if drop_writes configured
4306acd0 xenbus: don't look up transaction IDs for ordinary writes
189f6d32 timekeeping: Cap array access in timekeeping_debug
53cd25db ubifs: Fix assertion in layout_in_gaps()
e09bf151 Input: tegra-kbc - fix inverted reset logic
fc604c2a drm: Reject page_flip for !DRIVER_MODESET
a0d020d2 parisc: Fix order of EREFUSED define in errno.h
3838b8be ARC: export __udivdi3 for modules
d60e7f47 ARC: Support syscall ABI v4
c3716658 ARC: use correct offset in pt_regs for saving/restoring user mode r25
6c262bd1 ARCv2: STAR 9000808988: signals involving Delay Slot
61f53d4a Input: i8042 - set up shared ps2_cmd_mutex for AUX ports
0a47a530 drm/radeon: fix radeon_move_blit on 32bit systems
183e633e gpio: Fix OF build problem on UM
3dd120f4 bcache: RESERVE_PRIO is too small by one when prio_buckets() is a power of two.
472ea0f4 bcache: register_bcache(): call blkdev_put() when cache_alloc() fails
d1d55bb7 drm/radeon: only apply the SS fractional workaround to RS[78]80
ffdb240a drm/radeon: don't use fractional dividers on RS[78]80 if SS is enabled
f98192b6 uprobes: Fix the memcg accounting
cc2082d1 ARC: Elide redundant setup of DMA callbacks
63998a4d ARC: Call trace_hardirqs_on() before enabling irqs
8501430b usb: xhci: Fix panic if disconnect
d7fb5c37 xhci: always handle "Command Ring Stopped" events
cc29c033 cdc-acm: fix wrong pipe type on rx interrupt xfers
868f1a48 usb: misc: usbtest: add fix for driver hang
4b72a58f drm/i915: fix aliasing_ppgtt leak
1bc6efe0 usb: dwc3: gadget: always cleanup all TRBs
de72ed19 usb: dwc3: gadget: fix for short pkts during chained xfers
9bf46c6c usb: dwc3: gadget: increment request->actual once
c68f2d57 s390/dasd: fix hanging device after clear subchannel
64a45a08 usb: hub: Fix unbalanced reference count/memory leak/deadlocks
b7da50c8 crypto: caam - fix non-hmac hashes
30c2bbd8 aacraid: Check size values after double-fetch from user
8b0f82fc USB: serial: fix memleak in driver-registration error path
52b29d10 USB: serial: option: add support for Telit LE920A4
1fceecb5 USB: serial: ftdi_sio: add device ID for WICED USB UART dev board
b8d74e57 USB: serial: ftdi_sio: add PIDs for Ivium Technologies devices
a1ad7ce3 USB: serial: option: add D-Link DWM-156/A3
2e46bd05 mac80211: fix purging multicast PS buffer queue
0efba8d1 tcp: make challenge acks less predictable
399a4563 powerpc/eeh: eeh_pci_enable(): fix checking of post-request state
d45da77c Linux 3.18.40
8f03e30e perf/x86: Fix undefined shift on 32-bit kernels
3e287c23 nfsd: check permissions when setting ACLs
6abbd53f posix_acl: Add set_posix_acl
4f143eb4 powerpc/pseries: Fix PCI config address for DDW
79babf8a powerpc/iommu: Remove the dependency on EEH struct in DDW mechanism
8bc7adaf block: fix use-after-free in seq file
ddc1102b metag: Fix __cmpxchg_u32 asm constraint for CMP
71f1b13f ALSA: hda: add AMD Bonaire AZ PCI ID with proper driver caps
7dd90826 sysv, ipc: fix security-layer leaking
b4f191a7 mm/hugetlb: avoid soft lockup in set_max_huge_pages()
7154bbe8 dm flakey: error READ bios during the down_interval
8a7e3694 ftrace/recordmcount: Work around for addition of metag magic but not relocations
0335e86f balloon: check the number of available pages in leak balloon
40ca045f x86/syscalls/64: Add compat_sys_keyctl for 32-bit userspace
0ff4673f ALSA: hda/realtek: Enable HP amp and mute LED on HP Folio 9480m [v3]
b8463d76 drm/nouveau/fbcon: fix font width not divisible by 8
bd0e924c ubi: Make volume resize power cut aware
cdf25333 ubi: Fix race condition between ubi device creation and udev
6d1b8d7a fuse: fix wrong assignment of ->flags in fuse_send_init()
a8f8b0f5 fuse: fuse_flush must check mapping->flags for errors
689c2a89 fuse: fsync() did not return IO errors
77c6ffdb ARC: mm: don't loose PTE_SPECIAL in pte_modify()
2d6adadf drm/radeon: fix firmware info version checks
be17cd2e KEYS: 64-bit MIPS needs to use compat_sys_keyctl for 32-bit userspace
8c0c7bb9 KVM: PPC: Book3S HV: Save/restore TM state in H_CEDE
15b4c06d KVM: PPC: Book3S HV: Pull out TM state save/restore into separate procedures
1eaac174 CIFS: Fix a possible invalid memory access in smb2_query_symlink()
a10e07c7 fs/cifs: make share unaccessible at root level mountable
2bad2554 Input: i8042 - break load dependency between atkbd/psmouse and i8042
5a7dd70c Documentation/module-signing.txt: Note need for version info if reusing a key
1d307756 module: Invalidate signatures on force-loaded modules
29d011ab net/irda: fix NULL pointer dereference on memory allocation failure
5c0a3ca7 fs/dcache.c: avoid soft-lockup in dput()
ead2cea2 dcache: let the dentry count go down to zero without taking d_lock
cf4f30b2 nfs: don't create zero-length requests
f9fef43a gpio: intel-mid: Remove potentially harmful code
7b37bc27 iscsi-target: Fix panic when adding second TCP connection to iSCSI session
3f4976f0 audit: fix a double fetch in audit_log_single_execve_arg()
a59a2f6b Fix broken audit tests for exec arg len
c786cc5e audit: Fix check of return value of strnlen_user()
eeeec288 cifs: fix crash due to race in hmac(md5) handling
cb0a0062 target: Fix race between iscsi-target connection shutdown + ABORT_TASK
b4a8ca6b target: Fix missing complete during ABORT_TASK + CMD_T_FABRIC_STOP
bdcbb059 mtd: nand: fix bug writing 1 byte less than page size
8317c7f7 arm64: debug: unmask PSTATE.D earlier
57eed939 crypto: scatterwalk - Fix test in scatterwalk_done
6da47287 Bluetooth: Fix l2cap_sock_setsockopt() with optname BT_RCVMTU
b94d5a7f USB: serial: option: add support for Telit LE910 PID 0x1206
b2185081 powerpc/tm: Fix stack pointer corruption in __tm_recheckpoint()
9f4c899e powerpc/tm: Avoid SLB faults in treclaim/trecheckpoint when RI=0
69759a98 ext4: short-cut orphan cleanup on error
dc31456f drm/radeon: support backlight control for UNIPHY3
2aa2e066 KVM: nVMX: Fix memory corruption when using VMCS shadowing
6ef4fa7a usb: quirks: Add no-lpm quirk for Elan
84aec61c USB: quirks: Fix another ELAN touchscreen
5e33de12 s390/mm: fix gmap tlb flush issues
b2637b76 cifs: Check for existing directory when opening file with O_CREAT
d5dec668 [media] media: usbtv: prevent access to free'd resources
def5e119 Bluetooth: Add support of 13d3:3490 AR3012 device
77756a71 Bluetooth: Add USB ID 13D3:3487 to ath3k
9bf4930d [media] Fix RC5 decoding with Fintek CIR chipset
5d3e4a33 [media] media: dvb_ringbuffer: Add memory barriers
4b35be43 drm/radeon: Poll for both connect/disconnect on analog connectors
5a88bc52 drm/radeon: add a delay after ATPX dGPU power off
5467159c ext4: validate s_reserved_gdt_blocks on mount
926d244d ARM: dts: sunxi: Add a startup delay for fixed regulator enabled phys
94dd8b9a ext4: don't call ext4_should_journal_data() on the journal inode
aba6b2d8 ext4: fix deadlock during page writeback
cbe04d2b ext4: check for extents that wrap around
7d989fc4 usb: renesas_usbhs: protect the CFIFOSEL setting in usbhsg_ep_enable()
df09c563 usb: renesas_usbhs: fix NULL pointer dereference in xfer_work()
68960057 usb: renesas_usbhs: fix the sequence in xfer_work()
31338a15 hp-wmi: Fix wifi cannot be hard-unblocked
d918a2e1 serial: samsung: Fix ERR pointer dereference on deferred probe
b4d9416d of: fix memory leak related to safe_name()
8acc67b3 crypto: gcm - Filter out async ghash if necessary
c48db62d usb: dwc3: fix for the isoc transfer EP_BUSY flag
a5c2d04b Update my main e-mails at the Kernel tree
90777881 gpio: pca953x: Fix NBANK calculation for PCA9536
a83f985a PCI: Mark Atheros AR9485 and QCA9882 to avoid bus reset
4ed53b9d netlabel: add address family checks to netlbl_{sock,req}_delattr()
e2591cbc s5p-mfc: Add release callback for memory region devs
7cc9ce02 s5p-mfc: Set device name for reserved memory region devs
8f8b0fea HID: uhid: fix timeout when probe races with IO
43ba1649 Revert "drm/i915/ilk: Don't disable SSC source if it's in use"
6e0f6268 Linux 3.18.39
dcb5a62d x86/quirks: Reintroduce scanning of secondary buses
927dc15e x86/quirks: Apply nvidia_bugs quirk only on root bus
9c5125ac pps: do not crash when failed to register
b863398c radix-tree: fix radix_tree_iter_retry() for tagged iterators.
8777c9f6 libceph: apply new_state before new_up_client on incrementals
a7176826 libceph: set 'exists' flag for newly up osd
5eaee47b ovl: verify upper dentry in ovl_remove_and_whiteout()
a9d39310 tty/vt/keyboard: fix OOB access in do_compute_shiftstate()
e18fa5ad mmc: block: fix packed command header endianness
d380c88d media: fix airspy usb probe error path
5f51fe4b ALSA: hda: add AMD Stoney PCI ID with proper driver caps
1fcba7f0 ALSA: hda: add new AMD PCI IDs with proper driver caps
1a012d58 ALSA: hda - fix use-after-free after module unload
943e282c posix_cpu_timer: Exit early when process has been reaped
26c5fd38 x86/quirks: Add early quirk to reset Apple AirPort card
b001c42a net: mvneta: set real interrupt per packet for tx_done
77dee6b7 ALSA: ctl: Stop notification after disconnection
ee5dc420 ALSA: hda/realtek - add new pin definition in alc225 pin quirk table
a3638d4f ovl: Copy up underlying inode's ->i_mode to overlay inode
d4e1ac55 ovl: handle ATTR_KILL*
69fb704c drm/ttm: Make ttm_bo_mem_compat available
3837836c Input: xpad - validate USB endpoint count during probe
06c742fb ARM: mvebu: fix HW I/O coherency related deadlocks
f5bba514 netfilter: x_tables: speed up jump target validation
9a881c20 Revert "sparc64: Fix numa node distance initialization"
5d76452a Revert "MIPS: Reserve nosave data for hibernation"
0d1097ae Linux 3.18.38
52c84a95 4.1.28 Fix bad backport of 8f182270dfec "mm/swap.c: flush lru pvecs on compound page arrival"
da3e7add powerpc: Fix build break due to missing PPC_FEATURE2_HTM_NOSC
8c8e669b ecryptfs: don't allow mmap when the lower fs doesn't support it
050216f6 xen/acpi: allow xen-acpi-processor driver to load on Xen 4.7
38cd765b xenbus: don't bail early from xenbus_dev_request_and_reply()
e6e8b534 Revert "ecryptfs: forbid opening files without mmap handler"
19f46e35 xenbus: don't BUG() on user mode induced condition
12d75ae7 xenbus: Add proper handling of XS_ERROR from Xenbus for transactions.
aad82778 MIPS: Fix page table corruption on THP permission changes.
8c2cb775 qeth: delete napi struct when removing a qeth device
a851e568 ALSA: timer: Fix negative queue usage by racy accesses
b86ef7ef block: fix use-after-free in sys_ioprio_get()
82736d51 x86/amd_nb: Fix boot crash on non-AMD systems
fa48403a ALSA: au88x0: Fix calculation in vortex_wtdma_bufshift()
9f0a4f41 ipr: Clear interrupt on croc/crocodile when running with LSI
9d171576 ALSA: echoaudio: Fix memory allocation
0ac0a856 Linux 3.18.37
52a8202d tmpfs: fix regression hang in fallocate undo
6a9f9d4e netfilter: x_tables: introduce and use xt_copy_counters_from_user
aaa155f8 netfilter: x_tables: do compat validation via translate_table
edd8ae36 netfilter: x_tables: xt_compat_match_from_user doesn't need a retval
accd9c00 netfilter: ip6_tables: simplify translate_compat_table args
ad4ef8cc netfilter: ip_tables: simplify translate_compat_table args
cae1c6c2 netfilter: arp_tables: simplify translate_compat_table args
bbb7ecc8 netfilter: x_tables: don't reject valid target size on some architectures
3b94ada4 netfilter: x_tables: validate all offsets and sizes in a rule
7ba6a7df netfilter: x_tables: check for bogus target offset
c1380ecb netfilter: x_tables: check standard target size too
7ef13f49 netfilter: x_tables: add compat version of xt_check_entry_offsets
37a6fed6 netfilter: x_tables: assert minimum target size
dda46754 netfilter: x_tables: kill check_entry helper
62e6fd20 netfilter: x_tables: add and use xt_check_entry_offsets
674c7e17 netfilter: x_tables: validate targets of jumps
d1fe825e netfilter: x_tables: don't move to non-existent next rule
c2a1b8ee netfilter: x_tables: fix unconditional helper
66b7376b netfilter: x_tables: make sure e->next_offset covers remaining blob size
6a401cf3 netfilter: x_tables: validate e->target_offset early

Linux version 3.18.43-g0a417d7a16e8 (android-
    build@wpdt1.hot.corp.google.com) (gcc version 4.9.x 20150123
    (prerelease) (GCC) ) #1 SMP PREEMPT Wed May 10 18:32:29 UTC 2017

Bug: 34461621
Bug: 37293077
Bug: 37620681
Bug: 38117720
Test: Marlin boots, Maps, YouTube, Camera
Change-Id: I1826317f810475a3b58a7781bcf21ff0bd0c66a7
Source-Branch: android-msm-marlin-3.18
Signed-off-by: Martijn Coenen <maco@google.com>